SELECT B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(A.SALES_SUM * B.PRICE) AS TOTAL_SALES
FROM (SELECT BOOK_ID, SUM(SALES) AS SALES_SUM
        FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%'
        GROUP BY BOOK_ID) AS A
        JOIN BOOK B ON B.BOOK_ID = A.BOOK_ID
        JOIN AUTHOR C ON C.AUTHOR_ID = B.AUTHOR_ID
GROUP BY C.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC