-- 자동차 종류가 '세단' 또는 'SUV'
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 대여 금액이 50만원 이상 200만원 미만
-- 출력: 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트

SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, ROUND(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV')
    AND C.DURATION_TYPE = '30일 이상'
    AND A.CAR_ID NOT IN (SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE END_DATE >= '2022-11-01'
                        AND START_DATE <= '2022-11-30')
    AND ROUND(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30) >= 500000
    AND ROUND(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC