-- 평균 대여 기간 7일 이상
-- 자동차 ID, 평균 대여 기간(소수점 두번째 자리에서 반올림)

SELECT CAR_ID, ROUND(AVG(DATE_AVG), 1) AS AVERAGE_DURATION
FROM (SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DATE_AVG
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS A
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
