WITH AB AS (SELECT B.HISTORY_ID, A.CAR_TYPE, A.DAILY_FEE,
            DATEDIFF(B.END_DATE, B.START_DATE)+1 AS DATE_SUM,
            CASE 
                WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 90
                THEN '90일 이상'
                WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 30
                THEN '30일 이상'
                WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 7
                THEN '7일 이상'
                ELSE '7일 미만'
            END AS DURATION_TYPE
            FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
            ON A.CAR_ID = B.CAR_ID
            WHERE A.CAR_TYPE = '트럭')

SELECT AB.HISTORY_ID,
       ROUND(AB.DAILY_FEE / 100 * (100 - IFNULL(C.DISCOUNT_RATE, 0)) * AB.DATE_SUM, 0) AS FEE
FROM AB LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON AB.CAR_TYPE = C.CAR_TYPE AND AB.DURATION_TYPE = C.DURATION_TYPE
ORDER BY FEE DESC, AB.HISTORY_ID DESC