WITH FIRST AS (SELECT A.MEMBER_ID, A.MEMBER_NAME, SUM(B.REVIEW_SCORE) AS REVIEW_SUM
FROM MEMBER_PROFILE A JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
GROUP BY A.MEMBER_ID
ORDER BY REVIEW_SUM DESC
LIMIT 1)

SELECT FIRST.MEMBER_NAME, C.REVIEW_TEXT, DATE_FORMAT(C.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM FIRST JOIN REST_REVIEW C ON FIRST.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC